language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

install:
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - pipenv install --three --dev

script:
  - pipenv run pytest
  - pipenv run sphinx-build -nWT -b dummy doc doc/_build/html
